import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation files
const translations = {
  en: {
    // Navigation
    'nav.aboutUs': 'About Us',
    'nav.partners': 'Partners',
    'nav.program': 'Program',
    'nav.testimonials': 'Testimonials',
    'nav.timeline': 'Timeline',
    'nav.safety': 'Safety',
    'nav.studentRoles': 'Student Roles',
    'nav.scheduleCall': 'Schedule Discovery Call',
    'nav.joinCohort': 'Join Next Cohort',
    'nav.ecoblox': '3EcoBlox',
    
    // Hero Section
    'hero.title': 'Create on Roblox Engine.',
    'hero.title.environmental': 'Impact the Planet.',
    'hero.title.action': 'Inspire Millions.',
    'hero.description': '10-week program where students create real games while learning environmental problem-solving and digital citizenship',
    'hero.smallGroups': 'Small Groups',
    'hero.safeEnvironment': 'Safe Environment',
    'hero.realGameLaunch': 'Real Game Launch',
    'hero.scheduleCall': 'Schedule Discovery Call',
    'hero.watchSample': 'Watch Sample Class',
    'hero.tagline': 'Nurture digital native talent who think about the environment through games in a safe online environment!',
    'hero.environmentalFocus': 'Environmental Focus',
    'hero.realLearning': 'Real Learning',
    
    // Program Highlights
    'program.title': 'Why 3EcoBlox is Different',
    'program.description': 'Unlike traditional coding classes, 3EcoBlox combines environmental education, real game development, and digital citizenship in a comprehensive STEM program',
    'program.realGameDev': 'Real Game Development',
    'program.realGameDevDesc': 'Students build actual games in Roblox Studio that launch on our platform',
    'program.environmentalEdu': 'Environmental Education',
    'program.environmentalEduDesc': 'Every project addresses real environmental challenges and solutions',
    'program.teamCollab': 'Team Collaboration',
    'program.teamCollabDesc': 'Work in specialized roles with project management skills for real outcomes',
    'program.onlineSafety': 'Online Safety Training',
    'program.onlineSafetyDesc': 'Comprehensive digital citizenship and healthy gaming culture education',
    'program.actualLaunch': 'Actual Game Launch',
    'program.actualLaunchDesc': 'Games are published on Tamra Republic platform for real players',
    'program.technicalSkills': 'Technical Skills',
    'program.technicalSkillsDesc': 'Learn Lua scripting, 3D design, and project management fundamentals',
    
    // Game Plan
    'gameplan.title': 'Game Plan',
    'gameplan.description': 'Students create an interactive sustainability game where they manage energy resources and keep real-world events powered through smart upcycling',
    'gameplan.coreConcept': 'Core Concept: EV Battery Upcycling Game',
    'gameplan.mechanic.battery': 'Battery Conversion',
    'gameplan.mechanic.batteryDesc': 'Process used EV batteries into 1kWh blocks',
    'gameplan.mechanic.transport': 'Transportation',
    'gameplan.mechanic.transportDesc': 'Move blocks to exchange stations',
    'gameplan.mechanic.power': 'Power Management',
    'gameplan.mechanic.powerDesc': 'Supply energy to E-Charger Centers',
    'gameplan.mechanic.event': 'Event Success',
    'gameplan.mechanic.eventDesc': 'Keep concerts and events running',
    'gameplan.exampleTitle': 'Example: K-pop Concert Challenge',
    'gameplan.challenge': 'The Challenge',
    'gameplan.challengeDesc': 'A concert with 100 people requires 100 kWh per hour. For a 2-hour concert, students must supply 200 kWh total.',
    'gameplan.solution': 'The Solution',
    'gameplan.solutionDesc': 'Students process used EV batteries at the Battery Conversion Center, creating 200 individual 1kWh blocks.',
    'gameplan.stakes': 'The Stakes',
    'gameplan.stakesDesc': 'If supply runs low, the concert experiences a blackout! This teaches students that careful energy planning and teamwork are essential.',
    'gameplan.learningOutcomes': 'Learning Outcomes',
    'gameplan.outcome.energyPlanning': 'Energy planning and resource management',
    'gameplan.outcome.sustainabilityConcepts': 'Environmental sustainability concepts',
    'gameplan.outcome.collaboration': 'Collaborative problem-solving',
    'gameplan.outcome.realWorldStem': 'Real-world application of STEM skills',
    
    // Timeline
    'timeline.title': '10-Week Program Journey',
    'timeline.description': 'A structured learning path that takes students from introduction to game publication',
    'timeline.week1': 'Week 1',
    'timeline.week2to5': 'Week 2-5',
    'timeline.week6to9': 'Week 6-9',
    'timeline.week10': 'Week 10',
    'timeline.introduction': 'Introduction',
    'timeline.roleTraining': 'Role Training',
    'timeline.gameBuild': 'Game Build',
    'timeline.reviewPublish': 'Review & Publish',
    'timeline.kickoff': 'Program Kickoff',
    'timeline.skillDevelopment': 'Skill Development',
    'timeline.collaborativeDevelopment': 'Collaborative Development',
    'timeline.launchShowcase': 'Launch & Showcase',
    'timeline.kickoffDesc': 'Get familiar with the platform, safety guidelines, and basic concepts',
    'timeline.skillDesc': 'Learn specialized skills in your chosen role: Builder, Scripter, or Tester/Planner',
    'timeline.collaborativeDesc': 'Work as a team to build your environmental sustainability game',
    'timeline.launchDesc': 'Final testing, review, and publishing your game to the Tamra Republic platform',
    'timeline.stat.totalWeeks': 'Total Weeks',
    'timeline.stat.learningPhases': 'Learning Phases',
    'timeline.stat.publishedGame': 'Published Game',
    
    // Student Roles
    'roles.title': 'Choose Your Specialization',
    'roles.description': 'Every student chooses a role that matches their interests and strengths. All roles collaborate to create impactful environmental games.',
    'roles.chooseYourPath': 'Unlock Your Potential',
    'roles.pathSubtitle': 'Every student picks a specialization and contributes their unique skills',
    'roles.builder': 'Builder',
    'roles.builderSubtitle': '3D Design & Architecture',
    'roles.builderDesc': 'Create stunning 3D environments and structures that bring environmental concepts to life.',
    'roles.builderSkill1': '3D map design and architecture',
    'roles.builderSkill2': 'Environmental landscape creation',
    'roles.builderSkill3': 'Structural problem-solving',
    'roles.builderSkill4': 'Design thinking principles',
    'roles.scripter': 'Scripter',
    'roles.scripterSubtitle': 'Game Logic & Programming',
    'roles.scripterDesc': 'Write the code that makes environmental systems work and games come alive.',
    'roles.scripterSkill1': 'Game logic programming',
    'roles.scripterSkill2': 'Environmental system coding',
    'roles.scripterSkill3': 'Lua scripting in Roblox',
    'roles.scripterSkill4': 'Technical problem-solving',
    'roles.tester': 'Tester/Planner',
    'roles.testerSubtitle': 'Quality & Project Management',
    'roles.testerDesc': 'Ensure games work perfectly and projects stay on track for successful launches.',
    'roles.testerSkill1': 'Quality assurance processes',
    'roles.testerSkill2': 'Project management tools',
    'roles.testerSkill3': 'User experience testing',
    'roles.testerSkill4': 'Timeline and milestone management',
    'roles.skillsYoullLearn': 'Skills You\'ll Learn:',
    
    // Footer
    'footer.getStarted': 'Get Started',
    'footer.contactUs': 'Contact Us',
    'footer.brandDescription': 'Revolutionary STEM education program combining environmental education, coding, and project management through multiplayer game creation.',
    'footer.tagline': 'Nurture digital native talent who think about the environment through games in a safe online environment!',
    'footer.quick.program': 'Program',
    'footer.quick.programDetails': 'Program Details',
    'footer.quick.timeline': 'Timeline',
    'footer.quick.safety': 'Safety & Digital Citizenship',
    'footer.quick.roles': 'Student Roles',
    'footer.copyright': '© 2024 3EcoBlox. All rights reserved. Building the next generation of environmental innovators.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contactLink': 'Contact',

    // Roles labels
    'roles.keySkills': 'Key Skills:',
    'roles.exampleProjects': 'Example Projects:',
    'roles.learnMore': 'Learn More',

    // Program Highlight stats
    'program.stats.weeksProgram': 'Weeks Program',
    'program.stats.minutesPerClass': 'Minutes per Class',
    'program.stats.studentRoles': 'Student Roles',
    'program.stats.gameLaunchRate': 'Game Launch Rate',

    // Contact Popup
    'contact.title': 'Schedule Discovery Call',
    'contact.description': 'Get in touch with us to schedule your discovery call',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.gotIt': 'Got it!',

    // Value Props
    'valueProps.fun': 'Fun',
    'valueProps.funDesc': 'Build real games in Roblox while making a difference.',
    'valueProps.effective': 'Effective',
    'valueProps.effectiveDesc': 'Proven hands-on approach to STEM education.',
    'valueProps.backedByScience': 'Backed by Science',
    'valueProps.backedByScienceDesc': 'Research-based curriculum designed by educators.',
    'valueProps.stayMotivated': 'Stay Motivated',
    'valueProps.stayMotivatedDesc': 'Gamification, badges, and achievements keep students engaged.',
    'valueProps.personalizedLearning': 'Personalized Learning',
    'valueProps.personalizedLearningDesc': 'Choose your specialization: Builder, Scripter, or Tester.',

    // Learning Spaces
    'learningSpaces.title': 'Our Learning Spaces',
    'learningSpaces.subtitle': 'Explore our environmental education journey',

    // Special Pillars
    'specialPillars.title': 'What Makes EcoBlox Special?',
    'specialPillars.subtitle': 'Three powerful learning pillars in one program',
    'specialPillars.environmentalSTEM': 'Environmental STEM',
    'specialPillars.environmentalSTEMDesc': 'Tackle real-world environmental challenges through hands-on projects and problem-solving activities.',
    'specialPillars.robloxCoding': 'Roblox Coding',
    'specialPillars.robloxCodingDesc': 'Learn game development and coding fundamentals using Roblox Studio. Create real games while learning!',
    'specialPillars.digitalCitizenship': 'Digital Citizenship',
    'specialPillars.digitalCitizenshipDesc': 'Master online safety, digital ethics, and responsible technology use in a secure learning environment.',

    // Real World Gaming
    'realWorldGaming.title': 'Real-World Environmental Gaming',
    'realWorldGaming.subtitle': 'Students create actual energy systems through game development',
    'realWorldGaming.exampleTitle': 'Example: K-pop Concert Challenge',
    'realWorldGaming.challenge': 'The Challenge',
    'realWorldGaming.challengeDesc': 'A concert with 100 people requires 100 kWh per hour. For a 2-hour concert, students must supply 200 kWh total.',
    'realWorldGaming.solution': 'The Solution',
    'realWorldGaming.solutionDesc': 'Students process used EV batteries at the Battery Conversion Center, creating 200 individual 1kWh blocks.',
    'realWorldGaming.stakes': 'The Stakes',
    'realWorldGaming.stakesDesc': 'If supply runs low, the concert experiences a blackout! This teaches students that careful energy planning and teamwork are essential.',
    'realWorldGaming.learningOutcomes': 'Learning Outcomes',
    'realWorldGaming.outcome1': 'Energy planning and resource management',
    'realWorldGaming.outcome2': 'Environmental sustainability concepts',
    'realWorldGaming.outcome3': 'Collaborative problem-solving',
    'realWorldGaming.outcome4': 'Real-world application of STEM skills',
    'realWorldGaming.buildInRoblox': 'Build This System in Roblox!',
    'realWorldGaming.buildDesc': 'Students design the battery conversion center, program energy storage systems (ESS), create resource extraction mechanics, and simulate real-world energy challenges—all while learning about circular economy and sustainable technology.',

    // Timeline
    'timeline.title': 'Your Learning Path',
    'timeline.subtitle': 'Four steps to becoming an environmental game developer',
    'timeline.step1Title': 'Learn Environmental Science',
    'timeline.step1Desc': 'Start with engaging lessons about climate change, renewable energy, and ecosystem preservation. Understand the problems our planet faces.',
    'timeline.step2Title': 'Code in Roblox Studio',
    'timeline.step2Desc': 'Master Lua programming and game design fundamentals. Build interactive games with characters, obstacles, and environmental themes.',
    'timeline.step3Title': 'Create Your Game',
    'timeline.step3Desc': 'Combine your environmental knowledge with coding skills. Design a game that teaches others about sustainability and climate action.',
    'timeline.step4Title': 'Share & Celebrate',
    'timeline.step4Desc': 'Publish your game in a safe environment, share with family and friends, and celebrate your achievement as an environmental game developer!',

    // CTA Section
    'cta.title': 'Ready to Start Your Journey?',
    'cta.subtitle': 'Fun. Effective.',
    'cta.description': 'Join thousands of students learning to code while saving the planet with personalized, science-backed education!',
    'cta.stayMotivated': 'Stay Motivated',
    'cta.personalizedLearning': 'Personalized Learning',
    'cta.backedByScience': 'Backed by Science',
    'cta.startTrial': 'START TRIAL',

    // Parent Testimonials
    'parentTestimonials.title': 'What Parents Say',
    'parentTestimonials.subtitle': 'Hear from families who\'ve experienced the EcoBlox difference',
    'parentTestimonials.testimonial1.quote': 'I got the typical eye roll when I suggested EcoBlox to Vinny. But creating a battery recycling game transformed our dinner conversations into discussions about lithium waste and sustainability. EcoBlox meets kids where they are—through gaming—and suddenly they\'re engaged, motivated, and learning real-world problem-solving without realizing it.',
    'parentTestimonials.testimonial1.author': 'Deborah Vasquez',
    'parentTestimonials.testimonial1.role': 'Vinny\'s Mom (8th grader)',
    'parentTestimonials.testimonial2.quote': 'Our family moved from Korea, and EcoBlox became Benjamin\'s bridge—not just to coding, but to confidence. Watching him collaborate with peers to design a green energy game while improving his English has been remarkable. He\'s thinking critically about the planet\'s future in a way that feels natural and exciting.',
    'parentTestimonials.testimonial2.author': 'Linda Katz',
    'parentTestimonials.testimonial2.role': 'Benjamin\'s Mom (5th grader)',
    'parentTestimonials.testimonial3.quote': 'As an educator, I\'m particular about programs. EcoBlox exceeded expectations. Riddhi learned project management, environmental science, and teamwork through hands-on game creation. It\'s rare to find a program that builds both technical skills and environmental consciousness. The safe, structured approach gave me complete peace of mind.',
    'parentTestimonials.testimonial3.author': 'Kannan Santhoshini',
    'parentTestimonials.testimonial3.role': 'Riddhi\'s Mom (Parent & Educator)',
    'parentTestimonials.testimonial4.quote': 'Doyeul used to just consume games. Now he creates them—with purpose. Building a battery upcycling system taught him problem-solving and sustainability in ways traditional education never could. Seeing him excited to tackle environmental challenges through code makes me proud. This is education for the real world.',
    'parentTestimonials.testimonial4.author': 'Chris Lee',
    'parentTestimonials.testimonial4.role': 'Doyeul\'s Father (5th grader)',

    // Coach Testimonials
    'coachTestimonials.title': 'What Our Coaches Say',
    'coachTestimonials.subtitle': 'Hear from the educators guiding students on their learning journey',
    'coachTestimonials.testimonial1.quote': 'Teaching scripting at EcoBlox has been inspiring. Every class brings new discoveries as our students transform creative ideas into coded worlds. Each child approaches learning differently, but watching their confidence grow with every success reminds me why this work matters—it\'s about sparking imagination and building future innovators.',
    'coachTestimonials.testimonial1.author': 'Coach Abraham',
    'coachTestimonials.testimonial1.role': 'Tech Coach, EcoBlox',
    'coachTestimonials.testimonial2.quote': 'Team 1 has shown incredible growth through their K-Pop Battery Sustainability project. Despite initial challenges with coding and project management, our students bonded over shared interests and persevered. Watching them transform confusion into confidence while creating a game that promotes sustainability has been truly rewarding.',
    'coachTestimonials.testimonial2.author': 'Coach Johnny',
    'coachTestimonials.testimonial2.role': 'Project Management/Planner/Tester Coach, EcoBlox',
    'coachTestimonials.testimonial3.quote': 'Developing EcoBlox taught me that the best learning experiences combine passion with purpose. Our curriculum empowers students to become both creators and changemakers. Watching them code their own worlds while promoting sustainability shows the transformative power of project-based learning.',
    'coachTestimonials.testimonial3.author': 'Coach Jun',
    'coachTestimonials.testimonial3.role': 'Lead Coach, EcoBlox',

    // Partners Page
    'partners.title': 'Our Partners',
    'partners.subtitle': 'EcoBlox thrives through collaboration. We partner with parents, nonprofits, and companies to create meaningful educational experiences.',
    'partners.parents.title': 'Parents',
    'partners.parents.description': 'Join a community of parents dedicated to providing their children with innovative educational opportunities that go beyond traditional learning.',
    'partners.parents.button': 'Learn More',
    'partners.nonprofits.title': 'Nonprofits',
    'partners.nonprofits.description': 'Partner with us to expand your organization\'s impact and provide underserved communities with access to quality environmental education.',
    'partners.nonprofits.button': 'Learn More',
    'partners.companies.title': 'Companies',
    'partners.companies.description': 'Collaborate with EcoBlox to support STEM education, demonstrate corporate social responsibility, and invest in the future workforce.',
    'partners.companies.button': 'Learn More',

    // About Us Page
    'about.title': 'About Us',
    'about.welcome': 'Welcome to EcoBlox - where education meets innovation through game-based learning.',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'At EcoBlox, we are dedicated to transforming environmental education through engaging, game-based learning experiences. Our mission is to empower the next generation of environmental leaders through interactive and immersive educational programs.',
    'about.whatWeDo.title': 'What We Do',
    'about.whatWeDo.description': 'We provide comprehensive STEM and environmental education programs that combine real-world field experiences with virtual learning environments. Our innovative approach helps students develop critical thinking, problem-solving, and collaboration skills while learning about sustainability and environmental stewardship.',
    'about.approach.title': 'Our Approach',
    'about.approach.description': 'Through partnerships with schools, parents, nonprofits, and companies, we create meaningful learning experiences that prepare students for the challenges of tomorrow. Our game-based learning methodology ensures that education is not only effective but also engaging and fun.',

    // Parents Page
    'parentsPage.hero.title': 'Equipping Students with Future-Ready Skills',
    'parentsPage.hero.subtitle': 'As a parent, you want the best for your child, especially as the world shifts toward AI-driven industries. 3ecoblox programs are designed to cultivate the essential human skills that will complement, not compete with, future technology.',
    'parentsPage.vision.title': 'Our Vision for Parent Engagement',
    'parentsPage.vision.description': 'Your contribution—by enrolling and supporting your child—directly fuels their development into a confident, capable, and entrepreneurial leader.',
    'parentsPage.contribute.title': 'How Parents Contribute',
    'parentsPage.contribute.earlyExposure.title': 'Early Exposure',
    'parentsPage.contribute.earlyExposure.description': 'Enroll their children in 3ecoblox programs to ensure early exposure to critical 21st-century skills.',
    'parentsPage.contribute.shareFeedback.title': 'Share Feedback',
    'parentsPage.contribute.shareFeedback.description': 'Share feedback on student engagement and skill growth to help us continuously improve the learning experience.',
    'parentsPage.contribute.champion.title': 'Community Champion',
    'parentsPage.contribute.champion.description': 'Serve as a vocal champion within your community, helping to expand access to this essential education.',
    'parentsPage.testimonials.title': 'The Compelling Outcome: Testimonials',
    'parentsPage.testimonials.subtitle': 'Hear from parents about the transformation they\'ve seen in their children after participating in the 3ecoblox program:',
    'parentsPage.testimonials.skill1': 'Critical Thinking & Collaboration',
    'parentsPage.testimonials.skill2': 'Leadership & Technical Skills',
    'parentsPage.testimonials.skill3': 'Interdisciplinary Skills & Design Thinking',
    'parentsPage.testimonials.skill4': 'Screen Time to Creation Time',
    'parentsPage.cta.title': 'Ready to Get Started?',
    'parentsPage.cta.description': 'Join our next cohort and give your child the essential skills they need to thrive in an AI-driven future.',
    'parentsPage.cta.scheduleCall': 'Schedule Discovery Call',
    'parentsPage.cta.enrollChild': 'Enroll Your Child',

    // Nonprofit Page
    'nonprofitPage.hero.title': 'Amplifying Impact and Expanding Reach',
    'nonprofitPage.hero.subtitle': 'We are committed to helping non-profit organizations achieve their mission on a grander scale. By integrating our educational platform, we empower NPOs with global networking, amplified promotion, and a powerful new tool to engage their communities.',
    'nonprofitPage.vision.title': 'Our Vision for Non-Profit Collaboration',
    'nonprofitPage.vision.description': 'By integrating our educational platform, we empower non-profits with global networking capabilities, amplified promotion, and powerful tools to engage communities meaningfully.',
    'nonprofitPage.contribute.title': 'How Non-Profits Contribute',
    'nonprofitPage.contribute.integrate.title': 'Integrate Curricula',
    'nonprofitPage.contribute.integrate.description': 'Integrate 3ecoblox curricula into their existing educational and community outreach programs.',
    'nonprofitPage.contribute.cohost.title': 'Co-Host Challenges',
    'nonprofitPage.contribute.cohost.description': 'Co-host global innovation challenges related to their mission (e.g., a "Clean Water ecoblox Challenge").',
    'nonprofitPage.contribute.expertise.title': 'Provide Expertise',
    'nonprofitPage.contribute.expertise.description': 'Provide subject-matter expertise to ensure our lessons are grounded in real-world social and environmental issues.',
    'nonprofitPage.example.title': 'The Mutual Benefit: An Example',
    'nonprofitPage.example.partner': 'Partner Spotlight: Applied Computing Foundation',
    'nonprofitPage.example.description': 'Imagine the Applied Computing Foundation (ACF), a non-profit dedicated to closing the technology-access gap for underrepresented youth, partners with 3ecoblox.',
    'nonprofitPage.example.acf.title': 'Applied Computing Foundation\'s Benefit',
    'nonprofitPage.example.acf.network.title': 'Global Network & Promotion',
    'nonprofitPage.example.acf.network.description': 'ACF gains a global stage for their noble work, promoted across the entire 3ecoblox global network of schools, companies, and government entities, significantly boosting their visibility for grants and donations.',
    'nonprofitPage.example.acf.scalability.title': 'Program Scalability & Standardization',
    'nonprofitPage.example.acf.scalability.description': 'ACF can instantly scale its educational impact using the standardized and verified 3ecoblox modular curriculum, making it easier to train new instructors and launch programs in new geographies.',
    'nonprofitPage.example.acf.data.title': 'Measurable Impact Data',
    'nonprofitPage.example.acf.data.description': 'ACF can leverage 3ecoblox\'s platform to collect granular data on student progress in skills like computational thinking and collaborative problem-solving, providing concrete metrics for grant reports and donor stewardship.',
    'nonprofitPage.example.ecoblox.title': '3ecoblox\'s Contribution',
    'nonprofitPage.example.ecoblox.platform': '<strong>Global Platform:</strong> Access to our worldwide network of educational institutions, corporate partners, and government organizations for unprecedented reach.',
    'nonprofitPage.example.ecoblox.curriculum': '<strong>Ready-to-Deploy Curriculum:</strong> Proven, modular educational content that can be immediately integrated into existing programs without extensive development.',
    'nonprofitPage.example.ecoblox.analytics': '<strong>Analytics Infrastructure:</strong> Comprehensive tracking and reporting tools to measure and demonstrate impact to stakeholders and funders.',
    'nonprofitPage.cta.title': 'Let\'s Create Impact Together',
    'nonprofitPage.cta.description': 'Contact us to explore partnership opportunities and learn how 3ecoblox can help amplify your mission on a global scale.',
    'nonprofitPage.cta.button': 'Partner With Us',

    // Companies Page
    'companiesPage.hero.title': 'Driving Innovation Through Strategic Alliances',
    'companiesPage.hero.subtitle': 'At 3ecoblox, we believe that true innovation for a sustainable and technologically advanced future requires corporate synergy. We partner with forward-thinking companies to co-develop solutions, enhance product lines, and drive circular economy initiatives.',
    'companiesPage.vision.title': 'Our Vision for Corporate Collaboration',
    'companiesPage.vision.description': 'We partner with forward-thinking companies to co-develop solutions, enhance product lines, and drive circular economy initiatives that create lasting impact.',
    'companiesPage.contribute.title': 'How Companies Contribute',
    'companiesPage.contribute.data.title': 'Real-World Data',
    'companiesPage.contribute.data.description': 'Provide real-world data, challenges, and technical specifications for collaborative projects.',
    'companiesPage.contribute.expertise.title': 'Subject Matter Expertise',
    'companiesPage.contribute.expertise.description': 'Offer subject matter expertise for developing new ecoblox modules and curricula.',
    'companiesPage.contribute.mentorship.title': 'Industry Mentorship',
    'companiesPage.contribute.mentorship.description': 'Serve as industry mentors for student entrepreneurial teams, offering feedback and potential pilot opportunities.',
    'companiesPage.example.title': 'The Mutual Benefit: An Example',
    'companiesPage.example.partner': 'Partner Spotlight: Mobi Battery Recycling (South Korea)',
    'companiesPage.example.description': 'The challenge of electric vehicle (EV) battery recycling is a global issue, especially in high-adoption areas like Jeju Island, South Korea. Mobi Battery Recycling (or a similar entity working with Jeju Technopark) focuses on the evaluation and reuse of retired EV batteries for second-life applications like Energy Storage Systems (ESS) before final material extraction.',
    'companiesPage.example.mobi.title': 'Mobi Battery Recycling\'s Benefit',
    'companiesPage.example.mobi.talent.title': 'Applied R&D Talent Pipeline',
    'companiesPage.example.mobi.talent.description': '3ecoblox co-designs a curriculum where student teams develop AI-driven logistics models for battery collection/transport, or predictive maintenance algorithms for second-life ESS, providing Mobi with access to future talent and innovative solutions.',
    'companiesPage.example.mobi.esg.title': 'Enhanced Public & Investor Relations (ESG)',
    'companiesPage.example.mobi.esg.description': 'Partnership with 3ecoblox highlights Mobi\'s commitment to educational and social impact beyond their core business, strengthening their Environmental, Social, and Governance (ESG) profile to a global audience.',
    'companiesPage.example.mobi.poc.title': 'Proof-of-Concept & Efficiency Gains',
    'companiesPage.example.mobi.poc.description': 'Our global network of student teams can tackle complex, niche problems (e.g., maximizing material recovery from a specific battery chemistry) in a low-cost, high-innovation environment, providing Mobi with fresh technical insights.',
    'companiesPage.example.ecoblox.title': '3ecoblox\'s Contribution',
    'companiesPage.example.ecoblox.network': '<strong>Global Student Network:</strong> Access to talented student teams worldwide who can work on real-world challenges and provide innovative solutions.',
    'companiesPage.example.ecoblox.curriculum': '<strong>Curriculum Co-Development:</strong> Custom educational modules designed around your industry\'s specific challenges and technical requirements.',
    'companiesPage.example.ecoblox.esg': '<strong>ESG Amplification:</strong> Enhanced visibility and credibility for your sustainability and social impact initiatives across our global network.',
    'companiesPage.cta.title': 'Ready to Make an Impact?',
    'companiesPage.cta.description': 'Let\'s discuss how a strategic partnership with 3ecoblox can drive innovation, enhance your ESG profile, and create meaningful educational opportunities.',
    'companiesPage.cta.button': 'Explore Partnership Opportunities'
  },
  ko: {
    // Navigation
    'nav.aboutUs': '회사 소개',
    'nav.partners': '파트너',
    'nav.program': '프로그램',
    'nav.testimonials': '후기',
    'nav.timeline': '타임라인',
    'nav.safety': '안전',
    'nav.studentRoles': '학생 역할',
    'nav.scheduleCall': '상담 예약',
    'nav.joinCohort': '다음 기수 참여',
    'nav.ecoblox': '에코블록스',
    
    // Hero Section
    'hero.title': 'Roblox 엔진으로 만들기.',
    'hero.title.environmental': '지구에 영향 미치기.',
    'hero.title.action': '수백만 명에게 영감 주기.',
    'hero.description': '학생들이 환경 문제 해결과 디지털 시민의식을 배우며 실제 게임을 만드는 10주 프로그램',
    'hero.smallGroups': '소규모 그룹',
    'hero.safeEnvironment': '안전한 환경',
    'hero.realGameLaunch': '실제 게임 출시',
    'hero.scheduleCall': '상담 예약하기',
    'hero.watchSample': '샘플 수업 보기',
    'hero.tagline': '안전한 온라인 환경에서 게임을 통해 환경을 생각하는 디지털 네이티브 인재를 육성하세요!',
    'hero.environmentalFocus': '환경 중심',
    'hero.realLearning': '실제 학습',
    
    // Program Highlights
    'program.title': '에코블록스가 다른 이유',
    'program.description': '전통적인 코딩 수업과 달리, 에코블록스는 환경 교육, 실제 게임 개발, 디지털 시민의식을 포괄적인 STEM 프로그램으로 결합합니다',
    'program.realGameDev': '실제 게임 개발',
    'program.realGameDevDesc': '학생들이 우리 플랫폼에서 출시되는 실제 게임을 Roblox Studio에서 제작합니다',
    'program.environmentalEdu': '환경 교육',
    'program.environmentalEduDesc': '모든 프로젝트가 실제 환경 문제와 해결책을 다룹니다',
    'program.teamCollab': '팀 협력',
    'program.teamCollabDesc': '실제 결과를 위해 프로젝트 관리 기술과 전문 역할로 협력합니다',
    'program.onlineSafety': '온라인 안전 교육',
    'program.onlineSafetyDesc': '포괄적인 디지털 시민의식과 건전한 게임 문화 교육',
    'program.actualLaunch': '실제 게임 출시',
    'program.actualLaunchDesc': '게임이 실제 플레이어를 위해 Tamra Republic 플랫폼에 출판됩니다',
    'program.technicalSkills': '기술적 기술',
    'program.technicalSkillsDesc': 'Lua 스크립팅, 3D 디자인 및 프로젝트 관리 기본을 배우세요',
    
    // Game Plan
    'gameplan.title': '게임 계획',
    'gameplan.description': '학생들은 에너지 자원을 관리하고 스마트 업사이클링을 통해 실제 이벤트에 전력을 공급하는 상호작용 지속가능성 게임을 만듭니다',
    'gameplan.coreConcept': '핵심 개념: EV 배터리 업사이클링 게임',
    'gameplan.mechanic.battery': '배터리 전환',
    'gameplan.mechanic.batteryDesc': '사용된 EV 배터리를 1kWh 블록으로 가공',
    'gameplan.mechanic.transport': '운송',
    'gameplan.mechanic.transportDesc': '블록을 교환 스테이션으로 이동',
    'gameplan.mechanic.power': '전력 관리',
    'gameplan.mechanic.powerDesc': 'E-충전 센터에 에너지 공급',
    'gameplan.mechanic.event': '이벤트 성공',
    'gameplan.mechanic.eventDesc': '콘서트와 이벤트를 지속 운영',
    'gameplan.exampleTitle': '예시: K-pop 콘서트 챌린지',
    'gameplan.challenge': '도전 과제',
    'gameplan.challengeDesc': '100명의 관객이 있는 콘서트는 시간당 100kWh가 필요합니다. 2시간 콘서트에는 총 200kWh를 공급해야 합니다.',
    'gameplan.solution': '해결 방법',
    'gameplan.solutionDesc': '학생들은 배터리 전환 센터에서 사용된 EV 배터리를 가공하여 1kWh 블록 200개를 만듭니다.',
    'gameplan.stakes': '중요성',
    'gameplan.stakesDesc': '공급이 부족하면 콘서트가 정전됩니다! 이를 통해 세심한 에너지 계획과 팀워크의 중요성을 배웁니다.',
    'gameplan.learningOutcomes': '학습 성과',
    'gameplan.outcome.energyPlanning': '에너지 계획 및 자원 관리',
    'gameplan.outcome.sustainabilityConcepts': '환경 지속가능성 개념',
    'gameplan.outcome.collaboration': '협력적 문제 해결',
    'gameplan.outcome.realWorldStem': 'STEM 기술의 실제 적용',
    
    // Timeline
    'timeline.title': '10주 프로그램 여정',
    'timeline.description': '학생들을 소개부터 게임 출판까지 이끄는 구조화된 학습 경로',
    'timeline.week1': '1주차',
    'timeline.week2to5': '2-5주차',
    'timeline.week6to9': '6-9주차',
    'timeline.week10': '10주차',
    'timeline.introduction': '소개',
    'timeline.roleTraining': '역할 훈련',
    'timeline.gameBuild': '게임 제작',
    'timeline.reviewPublish': '검토 및 출판',
    'timeline.kickoff': '프로그램 시작',
    'timeline.skillDevelopment': '기술 개발',
    'timeline.collaborativeDevelopment': '협력 개발',
    'timeline.launchShowcase': '런칭 및 전시',
    'timeline.kickoffDesc': '플랫폼, 안전 가이드라인 및 기본 개념을 숙지하세요',
    'timeline.skillDesc': '선택한 역할에서 전문 기술을 배우세요: 빌더, 스크립터, 또는 테스터/플래너',
    'timeline.collaborativeDesc': '환경 지속가능성 게임을 만들기 위해 팀으로 협력하세요',
    'timeline.launchDesc': '최종 테스트, 검토 및 Tamra Republic 플랫폼에 게임 출판',
    'timeline.stat.totalWeeks': '총 주차',
    'timeline.stat.learningPhases': '학습 단계',
    'timeline.stat.publishedGame': '출판된 게임',
    
    // Student Roles
    'roles.title': '전문 분야 선택',
    'roles.description': '모든 학생은 자신의 관심사와 강점에 맞는 역할을 선택합니다. 모든 역할이 함께 협력하여 임팩트 있는 환경 게임을 만듭니다.',
    'roles.chooseYourPath': '전문 분야 선택',
    'roles.pathSubtitle': '모든 학생은 전문 분야를 선택하고 고유한 기술을 기여합니다',
    'roles.builder': '빌더',
    'roles.builderSubtitle': '3D 디자인 및 건축',
    'roles.builderDesc': '환경 개념을 생생하게 만드는 멋진 3D 환경과 구조물을 만드세요.',
    'roles.builderSkill1': '3D 맵 디자인 및 건축',
    'roles.builderSkill2': '환경 풍경 제작',
    'roles.builderSkill3': '구조적 문제 해결',
    'roles.builderSkill4': '디자인 사고 원칙',
    'roles.scripter': '스크립터',
    'roles.scripterSubtitle': '게임 로직 및 프로그래밍',
    'roles.scripterDesc': '환경 시스템이 작동하고 게임이 살아나도록 하는 코드를 작성하세요.',
    'roles.scripterSkill1': '게임 로직 프로그래밍',
    'roles.scripterSkill2': '환경 시스템 코딩',
    'roles.scripterSkill3': 'Roblox에서 Lua 스크립팅',
    'roles.scripterSkill4': '기술적 문제 해결',
    'roles.tester': '테스터/플래너',
    'roles.testerSubtitle': '품질 및 프로젝트 관리',
    'roles.testerDesc': '게임이 완벽하게 작동하고 프로젝트가 성공적인 출시를 위해 정상적으로 진행되도록 하세요.',
    'roles.testerSkill1': '품질 보증 프로세스',
    'roles.testerSkill2': '프로젝트 관리 도구',
    'roles.testerSkill3': '사용자 경험 테스트',
    'roles.testerSkill4': '타임라인 및 마일스톤 관리',
    'roles.skillsYoullLearn': '배울 기술:',
    
    // Footer
    'footer.getStarted': '시작하기',
    'footer.contactUs': '문의하기',
    'footer.brandDescription': '환경 교육, 코딩, 프로젝트 관리를 멀티플레이어 게임 제작과 결합한 혁신적인 STEM 교육 프로그램입니다.',
    'footer.tagline': '안전한 온라인 환경에서 게임을 통해 환경을 생각하는 디지털 네이티브 인재를 육성하세요!',
    'footer.quick.program': '프로그램',
    'footer.quick.programDetails': '프로그램 상세',
    'footer.quick.timeline': '타임라인',
    'footer.quick.safety': '안전 및 디지털 시민의식',
    'footer.quick.roles': '학생 역할',
    'footer.copyright': '© 2024 에코블록스. 모든 권리 보유. 환경 혁신가의 다음 세대를 양성합니다.',
    'footer.privacy': '개인정보 처리방침',
    'footer.terms': '이용 약관',
    'footer.contactLink': '문의',

    // Roles labels
    'roles.keySkills': '핵심 기술:',
    'roles.exampleProjects': '예시 프로젝트:',
    'roles.learnMore': '자세히 보기',

    // Program Highlight stats
    'program.stats.weeksProgram': '주 프로그램',
    'program.stats.minutesPerClass': '수업 당 분',
    'program.stats.studentRoles': '학생 역할',
    'program.stats.gameLaunchRate': '게임 출시율',

    // Contact Popup
    'contact.title': '상담 예약',
    'contact.description': '상담 예약을 위해 저희에게 연락해주세요',
    'contact.phone': '전화',
    'contact.email': '이메일',
    'contact.gotIt': '확인',

    // Value Props
    'valueProps.fun': '재미있는',
    'valueProps.funDesc': 'Roblox에서 실제 게임을 만들며 변화를 만들어보세요.',
    'valueProps.effective': '효과적인',
    'valueProps.effectiveDesc': '검증된 STEM 교육의 실습 중심 접근법.',
    'valueProps.backedByScience': '과학 기반',
    'valueProps.backedByScienceDesc': '교육자들이 설계한 연구 기반 커리큘럼.',
    'valueProps.stayMotivated': '동기 유지',
    'valueProps.stayMotivatedDesc': '게임화, 배지, 성취가 학생들의 참여를 유지합니다.',
    'valueProps.personalizedLearning': '맞춤형 학습',
    'valueProps.personalizedLearningDesc': '전문 분야를 선택하세요: 빌더, 스크립터, 또는 테스터.',

    // Learning Spaces
    'learningSpaces.title': '우리의 학습 공간',
    'learningSpaces.subtitle': '환경 교육 여정을 탐험하세요',

    // Special Pillars
    'specialPillars.title': 'EcoBlox만의 특별함',
    'specialPillars.subtitle': '하나의 프로그램에서 세 가지 강력한 학습 기둥',
    'specialPillars.environmentalSTEM': '환경 STEM',
    'specialPillars.environmentalSTEMDesc': '실습 프로젝트와 문제 해결 활동을 통해 실제 환경 문제에 도전하세요.',
    'specialPillars.robloxCoding': 'Roblox 코딩',
    'specialPillars.robloxCodingDesc': 'Roblox Studio를 사용하여 게임 개발 및 코딩 기초를 배우세요. 학습하면서 실제 게임을 만드세요!',
    'specialPillars.digitalCitizenship': '디지털 시민의식',
    'specialPillars.digitalCitizenshipDesc': '안전한 학습 환경에서 온라인 안전, 디지털 윤리, 책임 있는 기술 사용을 마스터하세요.',

    // Real World Gaming
    'realWorldGaming.title': '실제 환경 게이밍',
    'realWorldGaming.subtitle': '학생들이 게임 개발을 통해 실제 에너지 시스템을 만듭니다',
    'realWorldGaming.exampleTitle': '예시: K-pop 콘서트 챌린지',
    'realWorldGaming.challenge': '도전 과제',
    'realWorldGaming.challengeDesc': '100명의 관객이 있는 콘서트는 시간당 100kWh가 필요합니다. 2시간 콘서트에는 총 200kWh를 공급해야 합니다.',
    'realWorldGaming.solution': '해결 방법',
    'realWorldGaming.solutionDesc': '학생들은 배터리 전환 센터에서 사용된 EV 배터리를 가공하여 1kWh 블록 200개를 만듭니다.',
    'realWorldGaming.stakes': '중요성',
    'realWorldGaming.stakesDesc': '공급이 부족하면 콘서트가 정전됩니다! 이를 통해 세심한 에너지 계획과 팀워크의 중요성을 배웁니다.',
    'realWorldGaming.learningOutcomes': '학습 성과',
    'realWorldGaming.outcome1': '에너지 계획 및 자원 관리',
    'realWorldGaming.outcome2': '환경 지속가능성 개념',
    'realWorldGaming.outcome3': '협력적 문제 해결',
    'realWorldGaming.outcome4': 'STEM 기술의 실제 적용',
    'realWorldGaming.buildInRoblox': 'Roblox에서 이 시스템을 만들어보세요!',
    'realWorldGaming.buildDesc': '학생들은 배터리 전환 센터를 설계하고, 에너지 저장 시스템(ESS)을 프로그래밍하고, 자원 추출 메커니즘을 생성하고, 실제 에너지 챌린지를 시뮬레이션합니다—순환 경제와 지속 가능한 기술에 대해 배우면서 말이죠.',

    // Timeline
    'timeline.title': '학습 경로',
    'timeline.subtitle': '환경 게임 개발자가 되기 위한 4단계',
    'timeline.step1Title': '환경 과학 배우기',
    'timeline.step1Desc': '기후 변화, 재생 에너지, 생태계 보존에 대한 흥미로운 수업으로 시작하세요. 우리 지구가 직면한 문제를 이해하세요.',
    'timeline.step2Title': 'Roblox Studio에서 코딩하기',
    'timeline.step2Desc': 'Lua 프로그래밍과 게임 디자인 기초를 마스터하세요. 캐릭터, 장애물, 환경 테마가 있는 대화형 게임을 만드세요.',
    'timeline.step3Title': '게임 만들기',
    'timeline.step3Desc': '환경 지식과 코딩 기술을 결합하세요. 지속가능성과 기후 행동에 대해 다른 사람들에게 가르치는 게임을 디자인하세요.',
    'timeline.step4Title': '공유하고 축하하기',
    'timeline.step4Desc': '안전한 환경에서 게임을 게시하고, 가족 및 친구들과 공유하며, 환경 게임 개발자로서의 성취를 축하하세요!',

    // CTA Section
    'cta.title': '여정을 시작할 준비가 되셨나요?',
    'cta.subtitle': '재미있고. 효과적입니다.',
    'cta.description': '맞춤형 과학 기반 교육으로 지구를 구하면서 코딩을 배우는 수천 명의 학생들과 함께하세요!',
    'cta.stayMotivated': '동기 유지',
    'cta.personalizedLearning': '맞춤형 학습',
    'cta.backedByScience': '과학 기반',
    'cta.startTrial': '무료 체험 시작',

    // Parent Testimonials
    'parentTestimonials.title': '학부모님들의 이야기',
    'parentTestimonials.subtitle': 'EcoBlox의 차이를 경험한 가족들의 이야기를 들어보세요',
    'parentTestimonials.testimonial1.quote': '비니에게 EcoBlox를 제안했을 때 전형적인 눈 굴림을 받았습니다. 하지만 배터리 재활용 게임을 만들면서 저녁 식사 대화가 리튬 폐기물과 지속 가능성에 대한 토론으로 바뀌었습니다. EcoBlox는 아이들이 있는 곳, 즉 게임을 통해 만나고, 갑자기 그들은 참여하고, 동기부여되고, 깨닫지 못한 채 실제 문제 해결을 배우고 있습니다.',
    'parentTestimonials.testimonial1.author': '데보라 바스케스',
    'parentTestimonials.testimonial1.role': '비니의 엄마 (8학년)',
    'parentTestimonials.testimonial2.quote': '우리 가족은 한국에서 이주했고, EcoBlox는 벤자민의 다리가 되었습니다—코딩뿐만 아니라 자신감으로. 그가 동료들과 협력하여 녹색 에너지 게임을 디자인하면서 영어를 향상시키는 것을 보는 것은 놀라웠습니다. 그는 자연스럽고 흥미진진한 방식으로 지구의 미래에 대해 비판적으로 생각하고 있습니다.',
    'parentTestimonials.testimonial2.author': '린다 카츠',
    'parentTestimonials.testimonial2.role': '벤자민의 엄마 (5학년)',
    'parentTestimonials.testimonial3.quote': '교육자로서 저는 프로그램에 대해 까다롭습니다. EcoBlox는 기대를 초과했습니다. 리디는 실습 게임 제작을 통해 프로젝트 관리, 환경 과학 및 팀워크를 배웠습니다. 기술 능력과 환경 의식을 모두 구축하는 프로그램을 찾기는 드뭅니다. 안전하고 구조화된 접근 방식은 저에게 완전한 마음의 평화를 주었습니다.',
    'parentTestimonials.testimonial3.author': '칸난 산토시니',
    'parentTestimonials.testimonial3.role': '리디의 엄마 (부모 & 교육자)',
    'parentTestimonials.testimonial4.quote': '도열이는 게임을 소비만 했습니다. 이제 그는 목적을 가지고 게임을 만듭니다. 배터리 업사이클링 시스템을 구축하는 것은 전통적인 교육이 결코 할 수 없었던 방식으로 문제 해결과 지속 가능성을 가르쳤습니다. 그가 코드를 통해 환경 문제에 도전하는 것을 보면 자랑스럽습니다. 이것은 실제 세계를 위한 교육입니다.',
    'parentTestimonials.testimonial4.author': '크리스 리',
    'parentTestimonials.testimonial4.role': '도열이의 아버지 (5학년)',

    // Coach Testimonials
    'coachTestimonials.title': '코치들의 이야기',
    'coachTestimonials.subtitle': '학생들의 학습 여정을 안내하는 교육자들의 이야기를 들어보세요',
    'coachTestimonials.testimonial1.quote': 'EcoBlox에서 스크립팅을 가르치는 것은 영감을 주었습니다. 모든 수업은 학생들이 창의적인 아이디어를 코딩된 세계로 변환하면서 새로운 발견을 가져옵니다. 각 아이는 학습에 다르게 접근하지만, 성공할 때마다 자신감이 커지는 것을 보면 이 일이 중요한 이유를 상기시켜 줍니다—상상력을 불러일으키고 미래의 혁신가를 키우는 것입니다.',
    'coachTestimonials.testimonial1.author': '코치 아브라함',
    'coachTestimonials.testimonial1.role': '기술 코치, EcoBlox',
    'coachTestimonials.testimonial2.quote': '팀 1은 K-Pop 배터리 지속 가능성 프로젝트를 통해 놀라운 성장을 보여주었습니다. 코딩과 프로젝트 관리의 초기 어려움에도 불구하고, 학생들은 공유된 관심사를 통해 유대감을 형성하고 인내했습니다. 혼란을 자신감으로 변환하면서 지속 가능성을 홍보하는 게임을 만드는 것을 보는 것은 정말 보람 있었습니다.',
    'coachTestimonials.testimonial2.author': '코치 조니',
    'coachTestimonials.testimonial2.role': '프로젝트 관리/기획/테스터 코치, EcoBlox',
    'coachTestimonials.testimonial3.quote': 'EcoBlox를 개발하면서 최고의 학습 경험은 열정과 목적을 결합한다는 것을 배웠습니다. 우리의 커리큘럼은 학생들이 창조자이자 변화의 주체가 되도록 권한을 부여합니다. 지속 가능성을 홍보하면서 자신의 세계를 코딩하는 것을 보는 것은 프로젝트 기반 학습의 변혁적인 힘을 보여줍니다.',
    'coachTestimonials.testimonial3.author': '코치 준',
    'coachTestimonials.testimonial3.role': '리드 코치, EcoBlox',

    // Partners Page
    'partners.title': '파트너',
    'partners.subtitle': 'EcoBlox는 협력을 통해 번창합니다. 우리는 부모, 비영리 단체, 기업과 파트너십을 맺어 의미 있는 교육 경험을 만듭니다.',
    'partners.parents.title': '학부모',
    'partners.parents.description': '전통적인 학습을 넘어선 혁신적인 교육 기회를 자녀에게 제공하는 학부모 커뮤니티에 참여하세요.',
    'partners.parents.button': '자세히 보기',
    'partners.nonprofits.title': '비영리 단체',
    'partners.nonprofits.description': '조직의 영향력을 확대하고 소외된 지역 사회에 양질의 환경 교육을 제공하기 위해 협력하세요.',
    'partners.nonprofits.button': '자세히 보기',
    'partners.companies.title': '기업',
    'partners.companies.description': 'STEM 교육을 지원하고 기업의 사회적 책임을 입증하며 미래 인력에 투자하기 위해 EcoBlox와 협력하세요.',
    'partners.companies.button': '자세히 보기',

    // About Us Page
    'about.title': '회사 소개',
    'about.welcome': 'EcoBlox에 오신 것을 환영합니다 - 게임 기반 학습을 통해 교육과 혁신이 만나는 곳입니다.',
    'about.mission.title': '우리의 사명',
    'about.mission.description': 'EcoBlox에서 우리는 매력적인 게임 기반 학습 경험을 통해 환경 교육을 변화시키는 데 전념하고 있습니다. 우리의 사명은 상호작용적이고 몰입형 교육 프로그램을 통해 차세대 환경 리더를 육성하는 것입니다.',
    'about.whatWeDo.title': '우리가 하는 일',
    'about.whatWeDo.description': '우리는 실제 현장 경험과 가상 학습 환경을 결합한 종합적인 STEM 및 환경 교육 프로그램을 제공합니다. 우리의 혁신적인 접근 방식은 학생들이 지속 가능성과 환경 관리에 대해 배우면서 비판적 사고, 문제 해결 및 협업 기술을 개발하는 데 도움이 됩니다.',
    'about.approach.title': '우리의 접근 방식',
    'about.approach.description': '학교, 학부모, 비영리 단체 및 기업과의 파트너십을 통해 우리는 미래의 도전에 학생들을 준비시키는 의미 있는 학습 경험을 만듭니다. 우리의 게임 기반 학습 방법론은 교육이 효과적일 뿐만 아니라 매력적이고 재미있도록 보장합니다.',

    // Parents Page
    'parentsPage.hero.title': '미래 준비 기술을 갖춘 학생 육성',
    'parentsPage.hero.subtitle': '부모로서 세상이 AI 주도 산업으로 전환됨에 따라 자녀에게 최고를 원합니다. 3ecoblox 프로그램은 미래 기술과 경쟁하는 것이 아니라 보완할 필수 인간 기술을 배양하도록 설계되었습니다.',
    'parentsPage.vision.title': '학부모 참여에 대한 우리의 비전',
    'parentsPage.vision.description': '자녀를 등록하고 지원함으로써 귀하의 기여는 자녀가 자신감 있고 유능하며 기업가적인 리더로 발전하는 데 직접적으로 기여합니다.',
    'parentsPage.contribute.title': '학부모가 기여하는 방법',
    'parentsPage.contribute.earlyExposure.title': '조기 노출',
    'parentsPage.contribute.earlyExposure.description': '21세기 핵심 기술에 조기 노출을 보장하기 위해 자녀를 3ecoblox 프로그램에 등록하세요.',
    'parentsPage.contribute.shareFeedback.title': '피드백 공유',
    'parentsPage.contribute.shareFeedback.description': '학생 참여 및 기술 성장에 대한 피드백을 공유하여 학습 경험을 지속적으로 개선할 수 있도록 도와주세요.',
    'parentsPage.contribute.champion.title': '커뮤니티 챔피언',
    'parentsPage.contribute.champion.description': '커뮤니티 내에서 적극적인 옹호자 역할을 하여 이 필수 교육에 대한 접근성을 확대하는 데 도움을 주세요.',
    'parentsPage.testimonials.title': '설득력 있는 결과: 추천사',
    'parentsPage.testimonials.subtitle': '3ecoblox 프로그램에 참여한 후 자녀에게서 본 변화에 대한 학부모님들의 이야기를 들어보세요:',
    'parentsPage.testimonials.skill1': '비판적 사고 및 협력',
    'parentsPage.testimonials.skill2': '리더십 및 기술 능력',
    'parentsPage.testimonials.skill3': '학제 간 기술 및 디자인 사고',
    'parentsPage.testimonials.skill4': '스크린 타임에서 창작 시간으로',
    'parentsPage.cta.title': '시작할 준비가 되셨나요?',
    'parentsPage.cta.description': '다음 기수에 참여하여 자녀에게 AI 주도 미래에서 번영하는 데 필요한 필수 기술을 제공하세요.',
    'parentsPage.cta.scheduleCall': '상담 예약',
    'parentsPage.cta.enrollChild': '자녀 등록',

    // Nonprofit Page
    'nonprofitPage.hero.title': '영향력 확대 및 도달 범위 확장',
    'nonprofitPage.hero.subtitle': '우리는 비영리 조직이 더 큰 규모로 사명을 달성하도록 돕는 데 전념하고 있습니다. 교육 플랫폼을 통합함으로써 우리는 NPO에 글로벌 네트워킹, 증폭된 홍보 및 커뮤니티 참여를 위한 강력한 새 도구를 제공합니다.',
    'nonprofitPage.vision.title': '비영리 협력에 대한 우리의 비전',
    'nonprofitPage.vision.description': '교육 플랫폼을 통합함으로써 우리는 비영리 단체에 글로벌 네트워킹 기능, 증폭된 홍보 및 커뮤니티를 의미 있게 참여시킬 수 있는 강력한 도구를 제공합니다.',
    'nonprofitPage.contribute.title': '비영리 단체가 기여하는 방법',
    'nonprofitPage.contribute.integrate.title': '커리큘럼 통합',
    'nonprofitPage.contribute.integrate.description': '기존 교육 및 커뮤니티 지원 프로그램에 3ecoblox 커리큘럼을 통합합니다.',
    'nonprofitPage.contribute.cohost.title': '챌린지 공동 주최',
    'nonprofitPage.contribute.cohost.description': '사명과 관련된 글로벌 혁신 챌린지를 공동 주최합니다(예: "깨끗한 물 ecoblox 챌린지").',
    'nonprofitPage.contribute.expertise.title': '전문 지식 제공',
    'nonprofitPage.contribute.expertise.description': '실제 사회 및 환경 문제에 기반한 수업이 되도록 전문 지식을 제공합니다.',
    'nonprofitPage.example.title': '상호 이익: 예시',
    'nonprofitPage.example.partner': '파트너 스포트라이트: Applied Computing Foundation',
    'nonprofitPage.example.description': '소외된 청소년을 위한 기술 접근 격차를 해소하는 데 전념하는 비영리 단체인 Applied Computing Foundation(ACF)이 3ecoblox와 파트너십을 맺는다고 상상해 보세요.',
    'nonprofitPage.example.acf.title': 'Applied Computing Foundation의 혜택',
    'nonprofitPage.example.acf.network.title': '글로벌 네트워크 및 홍보',
    'nonprofitPage.example.acf.network.description': 'ACF는 3ecoblox 글로벌 네트워크의 학교, 기업 및 정부 기관 전체에 홍보되어 보조금 및 기부에 대한 가시성을 크게 높여 고귀한 작업을 위한 글로벌 무대를 얻습니다.',
    'nonprofitPage.example.acf.scalability.title': '프로그램 확장성 및 표준화',
    'nonprofitPage.example.acf.scalability.description': 'ACF는 표준화되고 검증된 3ecoblox 모듈식 커리큘럼을 사용하여 교육 영향을 즉시 확장할 수 있으므로 새로운 강사를 교육하고 새로운 지역에서 프로그램을 시작하기가 더 쉬워집니다.',
    'nonprofitPage.example.acf.data.title': '측정 가능한 영향 데이터',
    'nonprofitPage.example.acf.data.description': 'ACF는 3ecoblox 플랫폼을 활용하여 계산적 사고 및 협력적 문제 해결과 같은 기술에서 학생 진행 상황에 대한 세부 데이터를 수집하여 보조금 보고서 및 기부자 관리를 위한 구체적인 지표를 제공할 수 있습니다.',
    'nonprofitPage.example.ecoblox.title': '3ecoblox의 기여',
    'nonprofitPage.example.ecoblox.platform': '<strong>글로벌 플랫폼:</strong> 전례 없는 도달 범위를 위한 교육 기관, 기업 파트너 및 정부 조직의 전 세계 네트워크에 대한 액세스.',
    'nonprofitPage.example.ecoblox.curriculum': '<strong>즉시 배포 가능한 커리큘럼:</strong> 광범위한 개발 없이 기존 프로그램에 즉시 통합할 수 있는 검증된 모듈식 교육 콘텐츠.',
    'nonprofitPage.example.ecoblox.analytics': '<strong>분석 인프라:</strong> 이해 관계자 및 자금 제공자에게 영향을 측정하고 입증하기 위한 포괄적인 추적 및 보고 도구.',
    'nonprofitPage.cta.title': '함께 영향력을 만들어갑시다',
    'nonprofitPage.cta.description': '파트너십 기회를 탐색하고 3ecoblox가 귀하의 사명을 글로벌 규모로 확대하는 데 어떻게 도움이 되는지 알아보려면 문의하십시오.',
    'nonprofitPage.cta.button': '파트너 되기',

    // Companies Page
    'companiesPage.hero.title': '전략적 동맹을 통한 혁신 주도',
    'companiesPage.hero.subtitle': '3ecoblox에서는 지속 가능하고 기술적으로 발전된 미래를 위한 진정한 혁신에는 기업 시너지가 필요하다고 믿습니다. 우리는 미래 지향적인 기업과 파트너십을 맺어 솔루션을 공동 개발하고 제품 라인을 개선하며 순환 경제 이니셔티브를 추진합니다.',
    'companiesPage.vision.title': '기업 협력에 대한 우리의 비전',
    'companiesPage.vision.description': '우리는 미래 지향적인 기업과 파트너십을 맺어 솔루션을 공동 개발하고 제품 라인을 개선하며 지속적인 영향을 창출하는 순환 경제 이니셔티브를 추진합니다.',
    'companiesPage.contribute.title': '기업이 기여하는 방법',
    'companiesPage.contribute.data.title': '실제 데이터',
    'companiesPage.contribute.data.description': '협업 프로젝트를 위한 실제 데이터, 과제 및 기술 사양을 제공합니다.',
    'companiesPage.contribute.expertise.title': '전문 지식',
    'companiesPage.contribute.expertise.description': '새로운 ecoblox 모듈 및 커리큘럼 개발을 위한 전문 지식을 제공합니다.',
    'companiesPage.contribute.mentorship.title': '업계 멘토십',
    'companiesPage.contribute.mentorship.description': '학생 기업가 팀을 위한 업계 멘토 역할을 하며 피드백 및 잠재적 파일럿 기회를 제공합니다.',
    'companiesPage.example.title': '상호 이익: 예시',
    'companiesPage.example.partner': '파트너 스포트라이트: Mobi Battery Recycling (대한민국)',
    'companiesPage.example.description': '전기차(EV) 배터리 재활용 문제는 특히 대한민국 제주도와 같은 높은 채택 지역에서 글로벌 문제입니다. Mobi Battery Recycling(또는 제주 테크노파크와 협력하는 유사한 기관)은 최종 재료 추출 전에 에너지 저장 시스템(ESS)과 같은 2차 생활 애플리케이션을 위해 폐 EV 배터리의 평가 및 재사용에 중점을 둡니다.',
    'companiesPage.example.mobi.title': 'Mobi Battery Recycling의 혜택',
    'companiesPage.example.mobi.talent.title': '응용 R&D 인재 파이프라인',
    'companiesPage.example.mobi.talent.description': '3ecoblox는 학생 팀이 배터리 수집/운송을 위한 AI 기반 물류 모델 또는 2차 생활 ESS를 위한 예측 유지 관리 알고리즘을 개발하는 커리큘럼을 공동 설계하여 Mobi에 미래 인재 및 혁신적인 솔루션에 대한 액세스를 제공합니다.',
    'companiesPage.example.mobi.esg.title': '향상된 공공 및 투자자 관계 (ESG)',
    'companiesPage.example.mobi.esg.description': '3ecoblox와의 파트너십은 핵심 비즈니스를 넘어 교육 및 사회적 영향에 대한 Mobi의 헌신을 강조하여 글로벌 청중에게 환경, 사회 및 거버넌스(ESG) 프로필을 강화합니다.',
    'companiesPage.example.mobi.poc.title': '개념 증명 및 효율성 향상',
    'companiesPage.example.mobi.poc.description': '우리의 글로벌 학생 팀 네트워크는 저비용 고혁신 환경에서 복잡한 틈새 문제(예: 특정 배터리 화학에서 재료 회수 극대화)를 해결하여 Mobi에 새로운 기술 통찰력을 제공할 수 있습니다.',
    'companiesPage.example.ecoblox.title': '3ecoblox의 기여',
    'companiesPage.example.ecoblox.network': '<strong>글로벌 학생 네트워크:</strong> 실제 과제에 대해 작업하고 혁신적인 솔루션을 제공할 수 있는 전 세계의 재능 있는 학생 팀에 대한 액세스.',
    'companiesPage.example.ecoblox.curriculum': '<strong>커리큘럼 공동 개발:</strong> 업계의 특정 과제 및 기술 요구 사항을 중심으로 설계된 맞춤형 교육 모듈.',
    'companiesPage.example.ecoblox.esg': '<strong>ESG 증폭:</strong> 글로벌 네트워크 전반에 걸친 지속 가능성 및 사회적 영향 이니셔티브에 대한 가시성 및 신뢰성 향상.',
    'companiesPage.cta.title': '영향을 미칠 준비가 되셨나요?',
    'companiesPage.cta.description': '3ecoblox와의 전략적 파트너십이 어떻게 혁신을 주도하고 ESG 프로필을 개선하며 의미 있는 교육 기회를 창출할 수 있는지 논의해 봅시다.',
    'companiesPage.cta.button': '파트너십 기회 탐색'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language | null;
    return savedLanguage === 'ko' ? 'ko' : 'en';
  });

  useEffect(() => {
    // Save language preference
    localStorage.setItem('language', language);
  }, [language]);

  useEffect(() => {
    // Reflect language in HTML tag for accessibility and SEO
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
